#!/bin/csh
#$ -M zhu4@nd.edu     # Email address for job notification
#$ -m abe               # Send mail when job begins, ends and aborts
#$ -q gpu            
#$ -l gpu_card=1
#$ -N Conv       
 
module load python cuda/10.2

python mainPred.py train --layer=1 --data='CiteSeer' --rate=0.2
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
python mainPred.py train --layer=5 --data='CiteSeer' --rate=0.2
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
python mainPred.py train --layer=9 --data='CiteSeer' --rate=0.2
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
echo ----------------------------------------------------------------------
python mainPred.py train --layer=11 --data='CiteSeer' --rate=0.2
